name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Cache vcpkg
      uses: actions/cache@v2.1.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: vcpkg
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/*.a*') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: ${{ runner.os }}-vcpkg-

    - name: install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        ./vcpkg/bootstrap-vcpkg.sh

    - name: install dependencies
      run: ./vcpkg/vcpkg install libjpeg-turbo

    - name: configure
      run: |
        mkdir -p build
        cd build
        cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..

    - name: build
      run: cmake --build build --config Debug -j $(nproc)

    - name: test
      working-directory: build
      run: ctest -j $(nproc) --output-on-failure

    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
