name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'false'
    
    - uses: actions/cache@v2.1.3
      id: vcpkg-cache
      with:
        path: ${{runner.workspace}}/vcpkg/**
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/dependencies.vcpkg') }}
        restore-keys: |
            ${{ runner.os }}-vcpkg-
            ${{ runner.os }}-

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -j $(nproc)

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
